version: "3.8"
services:
    bot:
        image: "nikbaybal/bot_auto:latest"
        restart: "unless-stopped"
        env_file:
          - .env
        volumes:
          - type: bind
            source: my-project-2023-375610-9c983bcdb0e0.json
            target: /app/my-project-2023-375610-9c983bcdb0e0.json
